---
epochs: 30
batch_size: 10
net_divisor: 1
learning_rate: 0.001
num_workers: 12
img_dir_train: ../input/fruits/fruits-360/Training
img_dir_val: ../input/fruits/fruits-360/Training
img_dir_test: ../input/fruits/fruits-360/Test
img_out_dir: ../input/output/
models_dir: ../input/output/model

